update=04.03.2018 12:47:06
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32
LibName31=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName32=C:/Program Files/KiCad/share/kicad/library/74xx
LibName33=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName34=C:/Program Files/KiCad/share/kicad/library/actel
LibName35=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName36=C:/Program Files/KiCad/share/kicad/library/allegro
LibName37=C:/Program Files/KiCad/share/kicad/library/Altera
LibName38=C:/Program Files/KiCad/share/kicad/library/Amplifier_Audio
LibName39=C:/Program Files/KiCad/share/kicad/library/Amplifier_Buffer
LibName40=C:/Program Files/KiCad/share/kicad/library/Amplifier_Current
LibName41=C:/Program Files/KiCad/share/kicad/library/Amplifier_Difference
LibName42=C:/Program Files/KiCad/share/kicad/library/Amplifier_Instrumentation
LibName43=C:/Program Files/KiCad/share/kicad/library/Amplifier_Operational
LibName44=C:/Program Files/KiCad/share/kicad/library/Amplifier_Video
LibName45=C:/Program Files/KiCad/share/kicad/library/Analog
LibName46=C:/Program Files/KiCad/share/kicad/library/Analog_ADC
LibName47=C:/Program Files/KiCad/share/kicad/library/Analog_DAC
LibName48=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName49=C:/Program Files/KiCad/share/kicad/library/Analog_Switch
LibName50=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName51=C:/Program Files/KiCad/share/kicad/library/atmel
LibName52=C:/Program Files/KiCad/share/kicad/library/audio
LibName53=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName54=C:/Program Files/KiCad/share/kicad/library/bbd
LibName55=C:/Program Files/KiCad/share/kicad/library/bosch
LibName56=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName57=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName58=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName59=C:/Program Files/KiCad/share/kicad/library/Comparator
LibName60=C:/Program Files/KiCad/share/kicad/library/conn
LibName61=C:/Program Files/KiCad/share/kicad/library/Connector_Generic
LibName62=C:/Program Files/KiCad/share/kicad/library/Connector_Generic_Shielded
LibName63=C:/Program Files/KiCad/share/kicad/library/Connector_Specialized
LibName64=C:/Program Files/KiCad/share/kicad/library/contrib
LibName65=C:/Program Files/KiCad/share/kicad/library/Converter_ACDC
LibName66=C:/Program Files/KiCad/share/kicad/library/Converter_DCDC
LibName67=C:/Program Files/KiCad/share/kicad/library/CPLD_Altera
LibName68=C:/Program Files/KiCad/share/kicad/library/CPLD_Xilinx
LibName69=C:/Program Files/KiCad/share/kicad/library/CPU
LibName70=C:/Program Files/KiCad/share/kicad/library/CPU_NXP_6800
LibName71=C:/Program Files/KiCad/share/kicad/library/CPU_NXP_68000
LibName72=C:/Program Files/KiCad/share/kicad/library/CPU_PowerPC
LibName73=C:/Program Files/KiCad/share/kicad/library/cypress
LibName74=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName75=C:/Program Files/KiCad/share/kicad/library/device
LibName76=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName77=C:/Program Files/KiCad/share/kicad/library/diode
LibName78=C:/Program Files/KiCad/share/kicad/library/Diode_Bridge
LibName79=C:/Program Files/KiCad/share/kicad/library/Diode_Laser
LibName80=C:/Program Files/KiCad/share/kicad/library/display
LibName81=C:/Program Files/KiCad/share/kicad/library/Display_Character
LibName82=C:/Program Files/KiCad/share/kicad/library/Display_Graphic
LibName83=C:/Program Files/KiCad/share/kicad/library/Driver_Display
LibName84=C:/Program Files/KiCad/share/kicad/library/Driver_FET
LibName85=C:/Program Files/KiCad/share/kicad/library/Driver_LED
LibName86=C:/Program Files/KiCad/share/kicad/library/Driver_Motor
LibName87=C:/Program Files/KiCad/share/kicad/library/Driver_Relay
LibName88=C:/Program Files/KiCad/share/kicad/library/dsp
LibName89=C:/Program Files/KiCad/share/kicad/library/DSP_Freescale
LibName90=C:/Program Files/KiCad/share/kicad/library/DSP_Microchip_DSPIC33
LibName91=C:/Program Files/KiCad/share/kicad/library/DSP_Motorola
LibName92=C:/Program Files/KiCad/share/kicad/library/DSP_Texas
LibName93=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName94=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName95=C:/Program Files/KiCad/share/kicad/library/Filter
LibName96=C:/Program Files/KiCad/share/kicad/library/FPGA_Actel
LibName97=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx
LibName98=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Artix7
LibName99=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Kintex7
LibName100=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Spartan6
LibName101=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex5
LibName102=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex6
LibName103=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex7
LibName104=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName105=C:/Program Files/KiCad/share/kicad/library/gennum
LibName106=C:/Program Files/KiCad/share/kicad/library/GPU
LibName107=C:/Program Files/KiCad/share/kicad/library/graphic
LibName108=C:/Program Files/KiCad/share/kicad/library/hc11
LibName109=C:/Program Files/KiCad/share/kicad/library/intel
LibName110=C:/Program Files/KiCad/share/kicad/library/interface
LibName111=C:/Program Files/KiCad/share/kicad/library/Interface_CAN_LIN
LibName112=C:/Program Files/KiCad/share/kicad/library/Interface_CurrentLoop
LibName113=C:/Program Files/KiCad/share/kicad/library/Interface_Ethernet
LibName114=C:/Program Files/KiCad/share/kicad/library/Interface_Expansion
LibName115=C:/Program Files/KiCad/share/kicad/library/Interface_HID
LibName116=C:/Program Files/KiCad/share/kicad/library/Interface_LineDriver
LibName117=C:/Program Files/KiCad/share/kicad/library/Interface_Optical
LibName118=C:/Program Files/KiCad/share/kicad/library/Interface_Telecom
LibName119=C:/Program Files/KiCad/share/kicad/library/Interface_UART
LibName120=C:/Program Files/KiCad/share/kicad/library/Interface_USB
LibName121=C:/Program Files/KiCad/share/kicad/library/ir
LibName122=C:/Program Files/KiCad/share/kicad/library/Isolator
LibName123=C:/Program Files/KiCad/share/kicad/library/Isolator_Analog
LibName124=C:/Program Files/KiCad/share/kicad/library/Jumper
LibName125=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName126=C:/Program Files/KiCad/share/kicad/library/LED
LibName127=C:/Program Files/KiCad/share/kicad/library/leds
LibName128=C:/Program Files/KiCad/share/kicad/library/linear
LibName129=C:/Program Files/KiCad/share/kicad/library/Logic_74xgxx
LibName130=C:/Program Files/KiCad/share/kicad/library/Logic_74xx
LibName131=C:/Program Files/KiCad/share/kicad/library/Logic_CMOS_4000
LibName132=C:/Program Files/KiCad/share/kicad/library/Logic_CMOS_IEEE
LibName133=C:/Program Files/KiCad/share/kicad/library/Logic_LevelTranslator
LibName134=C:/Program Files/KiCad/share/kicad/library/Logic_Programmable
LibName135=C:/Program Files/KiCad/share/kicad/library/Logic_TTL_IEEE
LibName136=C:/Program Files/KiCad/share/kicad/library/logo
LibName137=C:/Program Files/KiCad/share/kicad/library/maxim
LibName138=C:/Program Files/KiCad/share/kicad/library/MCU_AnalogDevices
LibName139=C:/Program Files/KiCad/share/kicad/library/MCU_Atmel_8051
LibName140=C:/Program Files/KiCad/share/kicad/library/MCU_Atmel_ATMEGA
LibName141=C:/Program Files/KiCad/share/kicad/library/MCU_Atmel_ATTINY
LibName142=C:/Program Files/KiCad/share/kicad/library/MCU_Atmel_AVR
LibName143=C:/Program Files/KiCad/share/kicad/library/MCU_Cypress
LibName144=C:/Program Files/KiCad/share/kicad/library/MCU_Infineon
LibName145=C:/Program Files/KiCad/share/kicad/library/MCU_Intel
LibName146=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC10
LibName147=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC12
LibName148=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC16
LibName149=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC18
LibName150=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC24
LibName151=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC32
LibName152=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_SAME
LibName153=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_SAML
LibName154=C:/Program Files/KiCad/share/kicad/library/MCU_Module
LibName155=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_ColdFire
LibName156=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_HC11
LibName157=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_HC12
LibName158=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_HCS12
LibName159=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_Kinetis
LibName160=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_LPC
LibName161=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_MAC7100
LibName162=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_MCore
LibName163=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_S08
LibName164=C:/Program Files/KiCad/share/kicad/library/MCU_Parallax
LibName165=C:/Program Files/KiCad/share/kicad/library/MCU_SiFive
LibName166=C:/Program Files/KiCad/share/kicad/library/MCU_SiliconLabs
LibName167=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM8
LibName168=C:/Program Files/KiCad/share/kicad/library/MCU_Texas
LibName169=C:/Program Files/KiCad/share/kicad/library/MCU_Texas_MSP430
LibName170=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName171=C:/Program Files/KiCad/share/kicad/library/memory
LibName172=C:/Program Files/KiCad/share/kicad/library/Memory_Controller
LibName173=C:/Program Files/KiCad/share/kicad/library/Memory_EEPROM
LibName174=C:/Program Files/KiCad/share/kicad/library/Memory_EPROM
LibName175=C:/Program Files/KiCad/share/kicad/library/Memory_Flash
LibName176=C:/Program Files/KiCad/share/kicad/library/Memory_NVRAM
LibName177=C:/Program Files/KiCad/share/kicad/library/Memory_RAM
LibName178=C:/Program Files/KiCad/share/kicad/library/Memory_ROM
LibName179=C:/Program Files/KiCad/share/kicad/library/Memory_UniqueID
LibName180=C:/Program Files/KiCad/share/kicad/library/microchip
LibName181=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName182=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName183=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName184=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName185=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName186=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName187=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName188=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName189=C:/Program Files/KiCad/share/kicad/library/modules
LibName190=C:/Program Files/KiCad/share/kicad/library/Motor
LibName191=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName192=C:/Program Files/KiCad/share/kicad/library/motorola
LibName193=C:/Program Files/KiCad/share/kicad/library/motors
LibName194=C:/Program Files/KiCad/share/kicad/library/msp430
LibName195=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName196=C:/Program Files/KiCad/share/kicad/library/nxp
LibName197=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName198=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName199=C:/Program Files/KiCad/share/kicad/library/opto
LibName200=C:/Program Files/KiCad/share/kicad/library/Oscillator
LibName201=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName202=C:/Program Files/KiCad/share/kicad/library/philips
LibName203=C:/Program Files/KiCad/share/kicad/library/Potentiometer_Digital
LibName204=C:/Program Files/KiCad/share/kicad/library/power
LibName205=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName206=C:/Program Files/KiCad/share/kicad/library/Power_Protection
LibName207=C:/Program Files/KiCad/share/kicad/library/Power_Supervisor
LibName208=C:/Program Files/KiCad/share/kicad/library/powerint
LibName209=C:/Program Files/KiCad/share/kicad/library/pspice
LibName210=C:/Program Files/KiCad/share/kicad/library/Reference_Current
LibName211=C:/Program Files/KiCad/share/kicad/library/Reference_Voltage
LibName212=C:/Program Files/KiCad/share/kicad/library/references
LibName213=C:/Program Files/KiCad/share/kicad/library/regul
LibName214=C:/Program Files/KiCad/share/kicad/library/Regulator_Controller
LibName215=C:/Program Files/KiCad/share/kicad/library/Regulator_Current
LibName216=C:/Program Files/KiCad/share/kicad/library/Regulator_Linear
LibName217=C:/Program Files/KiCad/share/kicad/library/Regulator_SwitchedCapacitor
LibName218=C:/Program Files/KiCad/share/kicad/library/Regulator_Switching
LibName219=C:/Program Files/KiCad/share/kicad/library/Relay
LibName220=C:/Program Files/KiCad/share/kicad/library/Relay_SolidState
LibName221=C:/Program Files/KiCad/share/kicad/library/relays
LibName222=C:/Program Files/KiCad/share/kicad/library/RF
LibName223=C:/Program Files/KiCad/share/kicad/library/RF_AM_FM
LibName224=C:/Program Files/KiCad/share/kicad/library/RF_Bluetooth
LibName225=C:/Program Files/KiCad/share/kicad/library/RF_GPS
LibName226=C:/Program Files/KiCad/share/kicad/library/RF_Mixer
LibName227=C:/Program Files/KiCad/share/kicad/library/RF_Module
LibName228=C:/Program Files/KiCad/share/kicad/library/RF_RFID
LibName229=C:/Program Files/KiCad/share/kicad/library/RF_WiFi
LibName230=C:/Program Files/KiCad/share/kicad/library/RF_ZigBee
LibName231=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName232=C:/Program Files/KiCad/share/kicad/library/Sensor
LibName233=C:/Program Files/KiCad/share/kicad/library/Sensor_Audio
LibName234=C:/Program Files/KiCad/share/kicad/library/Sensor_Current
LibName235=C:/Program Files/KiCad/share/kicad/library/Sensor_Gas
LibName236=C:/Program Files/KiCad/share/kicad/library/Sensor_Humidity
LibName237=C:/Program Files/KiCad/share/kicad/library/Sensor_Magnetic
LibName238=C:/Program Files/KiCad/share/kicad/library/Sensor_Motion
LibName239=C:/Program Files/KiCad/share/kicad/library/Sensor_Optical
LibName240=C:/Program Files/KiCad/share/kicad/library/Sensor_Pressure
LibName241=C:/Program Files/KiCad/share/kicad/library/Sensor_Proximity
LibName242=C:/Program Files/KiCad/share/kicad/library/Sensor_Temperature
LibName243=C:/Program Files/KiCad/share/kicad/library/Sensor_Touch
LibName244=C:/Program Files/KiCad/share/kicad/library/Sensor_Voltage
LibName245=C:/Program Files/KiCad/share/kicad/library/sensors
LibName246=C:/Program Files/KiCad/share/kicad/library/silabs
LibName247=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName248=C:/Program Files/KiCad/share/kicad/library/stm8
LibName249=C:/Program Files/KiCad/share/kicad/library/stm32
LibName250=C:/Program Files/KiCad/share/kicad/library/supertex
LibName251=C:/Program Files/KiCad/share/kicad/library/Switch
LibName252=C:/Program Files/KiCad/share/kicad/library/switches
LibName253=C:/Program Files/KiCad/share/kicad/library/texas
LibName254=C:/Program Files/KiCad/share/kicad/library/Timer
LibName255=C:/Program Files/KiCad/share/kicad/library/Timer_PLL
LibName256=C:/Program Files/KiCad/share/kicad/library/Timer_RTC
LibName257=C:/Program Files/KiCad/share/kicad/library/transf
LibName258=C:/Program Files/KiCad/share/kicad/library/Transformer
LibName259=C:/Program Files/KiCad/share/kicad/library/Transistor_Array
LibName260=C:/Program Files/KiCad/share/kicad/library/Transistor_BJT
LibName261=C:/Program Files/KiCad/share/kicad/library/Transistor_FET
LibName262=C:/Program Files/KiCad/share/kicad/library/Transistor_IGBT
LibName263=C:/Program Files/KiCad/share/kicad/library/transistors
LibName264=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName265=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName266=C:/Program Files/KiCad/share/kicad/library/Valve
LibName267=C:/Program Files/KiCad/share/kicad/library/valves
LibName268=C:/Program Files/KiCad/share/kicad/library/video
LibName269=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName270=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName271=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName272=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName273=C:/Program Files/KiCad/share/kicad/library/zetex
LibName274=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName275=edu-buck-boost
